version: '3.3'

services:
   db:
     image: mysql:5.7
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     volumes:
       - ./db-dump:/docker-entrypoint-initdb.p
       - db_data:/var/lib/mysql

   phpmyadmin:
    depends_on: 
      - db
    image: corbinu/docker-phpmyadmin
    ports:
      - 8181:80
    environment: 
      MYSQL_USERNAME: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_PORT_3306_TCP_ADDR: db

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_DEBUG: 1
     working_dir: /var/www/html
     volumes:
       - ./wp-content:/var/www/html/wp-content
volumes:
    db_data: 
